name: flavor_chef
description: "Interactive CLI toolkit for setting up Flutter project flavors."
version: 0.1.0
homepage:

environment:
  sdk: ^3.8.1

dependencies:
  args: ^2.5.0
  collection: ^1.19.1
  path: ^1.9.0
  yaml: ^3.1.3
  yaml_edit: ^2.2.1

dev_dependencies:
  lints: ^3.0.0
  test: ^1.25.0

executables:
  flavor_chef: flavor_chef
